baseURL = 'https://blog.anvere.net/'
languageCode = 'en-us'
title = 'Anvere Blog'
theme = "papermod"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
comments = true
googleAnalytics = 'G-GBWQ1Q8Y49'